DROP TABLE MEMBERS;

CREATE TABLE STUDENTS(
    STUDENT_NUMBER      VARCHAR2(20),
    PASSWORD     VARCHAR2(30),
    STUDENT_NAME    VARCHAR2(50),
    CELL_PHONE   VARCHAR2(20),
    EMAIL        VARCHAR2(50),
    ADDRESS      VARCHAR2(200),
    GRADE        NUMBER,
    ADMISSION_YEAR DATE,
    GRADUATION_YEAR DATE,
    MAJOR VARCHAR(50),
    INTRODUCTION VARCHAR(200),
    REG_DATE     DATE DEFAULT SYSDATE,
    UPDATE_DATE  DATE DEFAULT SYSDATE,
    PRIMARY KEY(STUDENT_NUMBER)
);



drop table STUDENTS;


delete from STUDENTS 
where student_number = '20132000';



SELECT * FROM STUDENTS;

DELETE FROM MEMBERS
WHERE USER_ID = 'ahra';

CREATE TABLE AVATARS(
	STUDENT_NUMBER VARCHAR2(20) PRIMARY KEY,
	IMAGE BLOB
);

drop table avatars;

SELECT * FROM ATTACHMENTS;

COMMIT;

create table BOARDS (
   BOARD_ID NUMBER PRIMARY KEY,
   TITLE VARCHAR2(256) NOT NULL,
   CONTENT CLOB,
   WRITER  VARCHAR2(20) NOT NULL,
   READ_CNT NUMBER,
   REG_DATE DATE,
   UPDATE_DATE DATE
);

drop table BOARDS;

drop table ATTACHMENTS;

CREATE SEQUENCE BOARDS_SEQ;

CREATE TABLE ATTACHMENTS(
     ATTACHMENT_ID    NUMBER PRIMARY KEY,
     FILE_NAME        VARCHAR2(256),
     LOCATION       VARCHAR2(1024),
     BOARD_ID       NUMBER,
     REG_DATE        DATE,
     CONSTRAINT F_ATTACHMENTS_BOARD FOREIGN KEY(BOARD_ID)
     REFERENCES BOARDS(BOARD_ID)
);

CREATE SEQUENCE ATTACHMENTS_SEQ;


insert into boards values(boards_seq.nextval,'안녕하세요','구래구래구래','20132563',0,sysdate,sysdate);
insert into boards values(boards_seq.nextval,'안녕하세요22','구래구래구래','20132563',0,sysdate,sysdate);

drop table boards;
select * from boards;

COMMIT;

select * from ATTACHMENTS;




CREATE TABLE REPLIES( 
   REPLY_ID NUMBER PRIMARY KEY, 
   BOARD_ID NUMBER NOT NULL, 
   REPLY_LEVEL NUMBER, 
   PARENT NUMBER, 
   WRITER VARCHAR2(20) NOT NULL, 
   CONTENT VARCHAR2(1024), 
   DELETED NUMBER(1), 
   LIKE_CNT NUMBER,
   REG_DATE DATE, 
   UPDATE_DATE DATE, 
   CONSTRAINT F_REPLIES_BOARD FOREIGN KEY(BOARD_ID) REFERENCES BOARDS(BOARD_ID) ON DELETE CASCADE, 
   CONSTRAINT F_REPLIES_STUDENT FOREIGN KEY(WRITER) REFERENCES STUDENTS(STUDENT_NUMBER) ON DELETE SET NULL
);

drop table replies;

select * from replies;

CREATE SEQUENCE REPLIES_SEQ;

SELECT * FROM STUDENTS;
SELECT * FROM BOARDS;

ALTER TABLE BOARDS
ADD(WRITER_NAME VARCHAR(50));

UPDATE BOARDS
SET WRITER_NAME='dahye'
WHERE WRITER='20132563';



